name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Test npm access
        run: |
          echo "Testing npm access..."
          & "C:\Program Files\nodejs\npm.cmd" --version
        shell: powershell

      - name: Set PATH and Verify npm
        run: |
          $Env:PATH += ";C:\Program Files\nodejs"
          echo "New PATH: $Env:PATH"
          npm --version
        shell: powershell

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Bump version and push tag
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          DOCKER_IMAGE: robin/githubAction-test
        run: |
          # Insert your Docker build and push commands here
          # Example:
          docker build -t $DOCKER_IMAGE:latest .
          docker push $DOCKER_IMAGE:latest

          # The following lines are examples of what might follow, adjust as necessary
          VERSION=$(jq -r ".version" package.json)
          GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
          ENVIRONMENT="dev"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENVIRONMENT="prod"
          fi
          
          docker build -t $DOCKER_IMAGE:$ENVIRONMENT-$VERSION-$GIT_COMMIT_HASH .
          docker push $DOCKER_IMAGE:$ENVIRONMENT-$VERSION-$GIT_COMMIT_HASH
          
          if [ "$ENVIRONMENT" == "prod" ]; then
            docker tag $DOCKER_IMAGE:$ENVIRONMENT-$VERSION-$GIT_COMMIT_HASH $DOCKER_IMAGE:stable
            docker push $DOCKER_IMAGE:stable
          elif [ "$ENVIRONMENT" == "dev" ]; then
            docker tag $DOCKER_IMAGE:$ENVIRONMENT-$VERSION-$GIT_COMMIT_HASH $DOCKER_IMAGE:dev
            docker push $DOCKER_IMAGE:dev
