name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1'

      - name: Add Node.js to PATH
        run: echo "C:\Program Files\nodejs" >> $GITHUB_PATH

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Bump version and push tag
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        env:
          DOCKER_IMAGE: robin/githubAction-test
        run: |
          # Using full path to npm as a precaution
          'C:\Program Files\nodejs\npm.cmd' run build
          VERSION=$(jq -r ".version" package.json)
          GIT_COMMIT_HASH=$(git rev-parse --short HEAD)
          ENVIRONMENT="dev"
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENVIRONMENT="prod"
          fi
          
          # Build the Docker image
          docker build -t $DOCKER_IMAGE:$ENVIRONMENT-$VERSION-$GIT_COMMIT_HASH .
          
          # Push the Docker image with environment and commit hash tag
          docker push $DOCKER_IMAGE:$ENVIRONMENT-$VERSION-$GIT_COMMIT_HASH
          
          # Tag and push the image as either stable for prod or dev
          if [ "$ENVIRONMENT" == "prod" ]; then
            docker tag $DOCKER_IMAGE:$ENVIRONMENT-$VERSION-$GIT_COMMIT_HASH $DOCKER_IMAGE:stable
            docker push $DOCKER_IMAGE:stable
          elif [ "$ENVIRONMENT" == "dev" ]; then
            docker tag $DOCKER_IMAGE:$ENVIRONMENT-$VERSION-$GIT_COMMIT_HASH $DOCKER_IMAGE:dev
            docker push $DOCKER_IMAGE:dev
